name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - ipywidgets
  - notebook
  - ipykernel
  - nilearn
  - jupyterlab
  - nodejs
  - jupyterlab_widgets
  - pip
  - pip:
    - jupyterlab